# Generated by Django 2.2 on 2019-06-04 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instafish', '0002_auto_20190604_2347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='fish_length',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='fish_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='fish_weight',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='fishing_country',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
