# Generated by Django 2.2.1 on 2019-05-17 22:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instafish', '0002_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('yes', 'Wezmę udział'), ('no', 'Nie wezmę udziału'), ('idk', 'Niezdecydowany')], max_length=100)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instafish.Event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instafish.Profile')),
            ],
            options={
                'unique_together': {('user', 'event')},
            },
        ),
    ]
