# Generated by Django 2.2.1 on 2019-05-17 22:16

from django.db import migrations, models
import django.db.models.deletion
import django.utils.datetime_safe
import instafish.validators


class Migration(migrations.Migration):

    dependencies = [
        ('instafish', '0003_userevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.datetime_safe.datetime.utcnow, editable=False)),
                ('title', models.CharField(max_length=64)),
                ('fish_name', models.CharField(blank=True, max_length=200, null=True)),
                ('fish_weight', models.CharField(blank=True, max_length=200, null=True)),
                ('fish_length', models.CharField(blank=True, max_length=200, null=True)),
                ('fishing_country', models.CharField(blank=True, max_length=200, null=True)),
                ('fishing_city', models.CharField(blank=True, max_length=200, null=True)),
                ('fishing_date', models.DateField()),
                ('fish_photo', models.ImageField(upload_to='posts/', validators=[instafish.validators.validate_file_size])),
                ('fishing_reel', models.CharField(blank=True, max_length=200, null=True)),
                ('fishing_leader', models.CharField(blank=True, max_length=200, null=True)),
                ('fishing_hook', models.CharField(blank=True, max_length=200, null=True)),
                ('fishing_rod', models.CharField(blank=True, max_length=200, null=True)),
                ('fishing_bait', models.CharField(blank=True, max_length=200, null=True)),
                ('fishing_line', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField()),
                ('hashtag', models.CharField(blank=True, max_length=200, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instafish.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='PostLike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isLiked', models.BooleanField()),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instafish.Post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instafish.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instafish.Post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instafish.Profile')),
            ],
        ),
    ]
