# Generated by Django 2.2 on 2019-06-04 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instafish', '0004_auto_20190604_2359'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='achievements',
            new_name='achievement',
        ),
    ]
